<a href="https://colab.research.google.com/github/aswathi-coder/Linear_Regression/blob/main/Assignment_Linear__Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler

#### **1. Loading and Preprocessing **
##### ● Load the California Housing dataset using the fetch_california_housing function from sklearn.
##### ● Convert the dataset into a pandas DataFrame for easier handling. Handle missing values (if any) and perform necessary feature scaling (e.g., standardization).

In [ ]:
housing_data = fetch_california_housing()
df = pd.DataFrame(housing_data.data, columns=housing_data.feature_names)

In [ ]:
print(housing_data.data)

[[   8.3252       41.            6.98412698 ...    2.55555556
    37.88       -122.23      ]
 [   8.3014       21.            6.23813708 ...    2.10984183
    37.86       -122.22      ]
 [   7.2574       52.            8.28813559 ...    2.80225989
    37.85       -122.24      ]
 ...
 [   1.7          17.            5.20554273 ...    2.3256351
    39.43       -121.22      ]
 [   1.8672       18.            5.32951289 ...    2.12320917
    39.43       -121.32      ]
 [   2.3886       16.            5.25471698 ...    2.61698113
    39.37       -121.24      ]]

In [ ]:
print(df.columns)

Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude'],
      dtype='object')

In [ ]:
df.dtypes

MedInc        float64
HouseAge      float64
AveRooms      float64
AveBedrms     float64
Population    float64
AveOccup      float64
Latitude      float64
Longitude     float64
dtype: object

In [ ]:
df['Price'] = housing_data.target

##### Check Missing values

In [ ]:
df.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
Price         0
dtype: int64

In [ ]:
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [ ]:
df.shape

(20640, 9)

In [ ]:
# Seperate feature and target
x = df.drop('Price', axis=1)
y = df['Price']

In [ ]:
# Feature Scaling
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
# fit calculates the mean and standard deviation of each feature
# transform() convert it into a scaled value.
# StandardScaler return a NumPy array, so return it back to dataframe
x_scaled = pd.DataFrame(x_scaled,columns = x.columns)

##### **Explain the preprocessing steps you performed and justify why they are necessary for this dataset.**

##### First loaded the dataset and converted it into DataFrame. Then missing values are checked and found that there was no missing values. Regression model need independent and target variables, so seperated targeted variable. Feature scaling was performed using StandardScaler because different features have different ranges.

#### **2. Regression Algorithm Implementation**
##### ● Implement the following regression algorithms:
#####    ○ Linear Regression  
#####    ○ Decision Tree Regressor  
##### ● For each algorithm: Provide a brief explanation of how it works. Explain why it might be suitable for this dataset.

In [ ]:
# Linear Regression
# used for divide dataset into training and testing data
from sklearn.model_selection import train_test_split
# import linear regression algorithm
from sklearn.linear_model import LinearRegression
# Split dataset into training (80%) and testing data (20%)
x_train, x_test, y_train, y_test = train_test_split(x_scaled,y,test_size=0.2,random_state=42)
# random _state =42 ensures the same spllit every time.
lr_model = LinearRegression() # create linear regression model
lr_model.fit( x_train, y_train) # train model. Model learn the relationship between dependent and independent variales.
lr_predict = lr_model.predict( x_test) # Predict the house price
print(lr_predict)

[0.71912284 1.76401657 2.70965883 ... 4.46877017 1.18751119 2.00940251]

#####  Linear regression is a simple algorithm. Here in this dataset, it identifies the relationship between the housing features and price. By providing 80% of training it learned the model well and predict the house price.

In [ ]:
# Decision Tree Regressor
from sklearn.tree import DecisionTreeRegressor # Import DecisionTreeRenerator algorithm
dt_model = DecisionTreeRegressor(random_state=42) # Create DecisionTreeRenerator model
dt_model.fit(x_train,y_train) # It split data into decision rules.
dt_predict = dt_model.predict(x_test) # Predict the value
print(dt_predict)

[0.414   1.203   5.00001 ... 5.00001 0.66    2.172  ]

##### Rather than linear relation decision trees can consider nonlinear relationships to predict the house price

#### Model Evaluation and Comparison
##### ● Evaluate the performance of each algorithm using the following metrics:
##### ○ Mean Squared Error (MSE)  
##### ○ Mean Absolute Error (MAE)  
##### ○ R-squared Score (R²)

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
result = {}

In [ ]:
# Evaluate linear Regression Model
result['Linear Regression'] = [
    mean_squared_error(y_test, lr_predict),
    mean_absolute_error(y_test, lr_predict),
    r2_score(y_test, lr_predict)
]

In [ ]:
# Decision Tree Regressor
result['Decision Tree Regressor'] = [
    mean_squared_error(y_test, dt_predict),
    mean_absolute_error(y_test, dt_predict),
    r2_score(y_test, dt_predict)
]

In [ ]:
# Convert Results into DataFrame
results_df = pd.DataFrame(
    result,
    index=['MSE','MAE','R2 Score']
)
print(results_df)

          Linear Regression  Decision Tree Regressor
MSE                0.555892                 0.494272
MAE                0.533200                 0.453784
R2 Score           0.575788                 0.622811

##### **Compare the results of all models and identify: The best-performing algorithm with justification.**
##### The Decision Tree Regressor is the best-performing model among the tested algorithms. It achieved the lowest MSE and MAE values and the highest R² score, indicating better prediction accuracy. The model can capture non-linear relationships between housing features and house prices, which improves its performance compared to Linear Regression.